# -*- coding: utf-8 -*-
"""Assignment_5(list, tupel)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRs5QZ524xyudtgn9u0BUu3XJgYNWDn3

Assignment 5 (01/11/2022)
"""

first_list = ['abcd', 147, 2.43, 'Tom', 74.8]
first_list

first_list[0]

first_list[1:3]

first_list[2:]

print(len(first_list))

"""2) Small_list"""

small_list = [222, 'Tom']
small_list

for i in range(2):
  print(small_list)

#final_list = first_list + small_list
#final_list
for i in first_list:
  small_list.append(i)
small_list

"""Tuple"""

first_tuple = ('abcd', 147, 2.43, 'Tom', 74.8)
first_tuple

first_tuple[0]

first_tuple[1:3]

first_tuple[2:]

print(len(first_tuple))

small_tuple = (222, 'Tom')
small_tuple

for i in range(2):
  print(small_tuple)

for i in small_tuple:
  first_tuple.append(i)
first_tuple

import math
def check_prime(n):
    if n == 1:
        return False
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            return False
    return True
x = int(input("enter number: "))
if check_prime(x):
    print(x, "is prime number")
else:
    print(x, "is not prime")

for i in range(1, 5):
    print(i)

my_list = [12, 13, 11, 2, 6, 23, 17, 18, 19]
my_list_1 = [x for x in my_list if x % 2 != 0]
print(my_list_1)
for item in my_list:
    if item % 2 == 0:
        my_list.remove(item)
print(my_list)